spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3307/news_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Anakin!123
      stat-view-servlet:
        login-username: admin
        login-password: admin
